spring:
  application:
    name: receipt-processor
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:receipts
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
